### ISSUE TITLE
Setting own Model

### ISSUE THREAD

**Issue by webleyson** [bitfumes/laravel-multiauth#132]
**Describe the bug**
In the docs it says you can set your own Admin model

https://bitfumes.github.io/laravel-multiauth/settings.html#models

I have set the following

<code> 'admin'          => App\Admin::class,</code>

But this has no affect. I have set in - vendors/config/auth.php and it sets.  

What am I doing wrong?

**Laravel Version**
7.24

**To Reproduce**
1. Go to 'config/multiauth.php'
2. Set model to local model - app/Admin.php
3.          dd(Auth::guard('admin')->user());
4. See error - Not the App/Admin auth

**Expected behavior**
Expected to see admin from my app folder

**Comment by sarthaksavvy** [comment]
This is now fixed with new version
try 5.2.0

**Comment by webleyson** [comment]
This is still not fixed..
'models' => [
        'admin'          => App\Admin::class,
        'role'           => Bitfumes\Multiauth\Model\Role::class,
        'permission'     => Bitfumes\Multiauth\Model\Permission::class,
    ],

 dd(Auth::guard('admin')->user());

is still showing - 

Bitfumes\Multiauth\Model\Admin
